### ISSUE TITLE
Base image

### ISSUE THREAD

**Issue by Kacperek0** [iLoveReact/minecraftDocker#2]
https://github.com/iLoveReact/minecraftDocker/blob/32d18bae99fd31bc350293322485928028e9a3f2/Dockerfile#L1C1-L1C12

Starting from ubuntu base image is bringing tonnes of unnecessary things to the container. Container should have as little as possible to run the application.

Maybe, just maybe, there's a way to start from an image which already has openjdk installed. Please check [here](https://hub.docker.com/_/openjdk/)

**Comment by iLoveReact** [comment]
You are right. I did not think about that :0. I changed it to openjdk:17.
